# Generated by Django 3.2.25 on 2025-02-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xsrconfiguration',
            name='source_file',
        ),
        migrations.AddField(
            model_name='xsrconfiguration',
            name='Parameter',
            field=models.JSONField(blank=True, null=True, verbose_name='Enter parameters '),
        ),
        migrations.AddField(
            model_name='xsrconfiguration',
            name='Subscription_key',
            field=models.CharField(blank=True, help_text='Enter the XSR Token', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='xsrconfiguration',
            name='Transcript_API',
            field=models.CharField(default='.com', help_text='Enter the ACE Transcript API endpoint', max_length=200),
            preserve_default=False,
        ),
    ]
