# Generated by Django 3.2.25 on 2025-03-05 19:02

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250210_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsrconfiguration',
            name='API_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='Course', max_length=100, no_check_for_status=True),
        ),
    ]
