# Generated by Django 3.2.25 on 2025-09-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_xsrconfiguration_api_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsrconfiguration',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='xsrconfiguration',
            name='Subscription_key',
            field=models.CharField(blank=True, default='', help_text='Enter the XSR Token', max_length=200),
        ),
        migrations.AlterField(
            model_name='xsrconfiguration',
            name='Transcript_API',
            field=models.CharField(blank=True, help_text='Enter the ACE Transcript API endpoint', max_length=200),
        ),
    ]
