# Generated by Django 3.2.25 on 2025-09-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250923_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xsrconfiguration',
            name='source_file',
            field=models.FileField(blank=True, help_text='Upload JSON file ', null=True, upload_to='source/'),
        ),
    ]
