# Generated by Django 3.2.25 on 2025-10-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_xsrconfiguration_source_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xsrconfiguration',
            name='source_file',
        ),
        migrations.AddField(
            model_name='xsrconfiguration',
            name='s3_source_file',
            field=models.CharField(blank=True, help_text='Enter the S3 source file path', max_length=500),
        ),
        migrations.AlterField(
            model_name='xsrconfiguration',
            name='Subscription_key',
            field=models.CharField(blank=True, help_text='Enter the XSR Token', max_length=200),
        ),
    ]
